dist: bionic

os:
  - linux

branches:
  only:
  - master

services:	
  - docker

arch:
  - aarch64

addons:
  apt:
    update: true
  hosts:
    - node2

# Build Test
script:
  - cd openEuler20.03
  - if [  "$(uname -m)" == "aarch64" ]; then
      docker build -t kunpengcompute/openeuler:rpmbuild.aarch64 -t kunpengcompute/openeuler:rpmbuild aarch64;
    else
      docker build -t kunpengcompute/openeuler:rpmbuild.x86_64 x86_64;
    fi
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kunpengcompute/openeuler:rpmbuild.aarch64
  - docker push kunpengcompute/openeuler:rpmbuild
