dist: bionic

os:
  - linux

branches:
  only:
  - master

arch:
  - aarch64

addons:
  apt:
    update: true
  hosts:
    - node2

# Build Test
script:
  - sudo apt-get install docker.io
  - cd openEuler20.03
  - docker build -t kunpengcompute/openeuler:rpmbuild.aarch64 -t kunpengcompute/openeuler:rpmbuild aarch64
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kunpengcompute/openeuler:rpmbuild.aarch64
  - docker push kunpengcompute/openeuler:rpmbuild
